# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

italicized text## Delete

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
# In order to ignore FutureWarning
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [0]:
from sklearn.datasets import load_iris
iris = load_iris()

In [0]:
type(iris)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [0]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [0]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [0]:
import numpy as np

In [0]:
np.isnan(iris.data).any()

False

In [0]:
print(iris.data[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [0]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [0]:
X = iris.data
Y = iris.target

In [0]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
print(X.shape, X.ndim, Y.shape, Y.ndim)

(150, 4) 2 (150,) 1


In [0]:
#convert Label to 2 dimensional array
#y_ = iris.target.reshape(-1, 1)

In [0]:
#y_.ndim

In [0]:
#y_.shape

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=7)

In [0]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 4) (38, 4) (112,) (38,)


In [0]:
#X_train, X_test, y_train, y_test = train_test_split(X, y_, test_size=0.25, random_state=7)

In [0]:
#print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

In [0]:
# Import `StandardScaler` from `sklearn.preprocessing`
from sklearn.preprocessing import StandardScaler

# Define the scaler 
scaler = StandardScaler().fit(X_train)

# Scale the train set
X_train = scaler.transform(X_train)

# Scale the test set
X_test = scaler.transform(X_test)

In [0]:
print(X_train.ndim, X_test.ndim, y_train.ndim, y_test.ndim)

2 2 1 1


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
#encode

def encode(labels):
    print("Shape of data (BEFORE encode): %s" % str(labels.shape))
    encoded = tf.keras.utils.to_categorical(labels, num_classes = 3, dtype = "float32")
    print("Shape of data (AFTER encode): %s" % str(encoded.shape))
    return encoded

In [0]:
encoded_y_train = encode(y_train)
print(encoded_y_train)

Shape of data (BEFORE encode): (112,)
Shape of data (AFTER encode): (112, 3)
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]

In [0]:
encoded_y_test = encode(y_test)
print(encoded_y_test)

Shape of data (BEFORE encode): (38,)
Shape of data (AFTER encode): (38, 3)
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [0]:
#Initialize Sequential model
model = Sequential()


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add input layer
model.add(Dense(30, input_shape=(4,), activation='relu', name='input_layer'))

In [0]:
#Add 1st hidden layer
model.add(Dense(4, activation='relu'))

In [0]:
#Add 2nd hidden layer
model.add(Dense(4, activation='relu'))

In [0]:
#model.add(Dense(10,activation='relu'))

In [0]:
#Add Output layer
model.add(Dense(3, activation='softmax', name='output_layer'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#Create optimizer with non-default learning rate
#sgd_optimizer = tf.keras.optimizers.SGD

#Compile the model
model.compile(optimizer="sgd", loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
model.build(input_shape=(4,))

In [131]:
print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 30)                150       
_________________________________________________________________
dense_10 (Dense)             (None, 4)                 124       
_________________________________________________________________
dense_11 (Dense)             (None, 4)                 20        
_________________________________________________________________
output_layer (Dense)         (None, 3)                 15        
Total params: 309
Trainable params: 309
Non-trainable params: 0
_________________________________________________________________
None


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [136]:
model.fit(X_train,encoded_y_train,batch_size=50, epochs=200,verbose=1,validation_data=(X_test,encoded_y_test))

Train on 112 samples, validate on 38 samples
Epoch 1/200
112/112 [==============================] - 0s 165us/sample - loss: 0.1977 - accuracy: 0.9732 - val_loss: 0.3716 - val_accuracy: 0.8684
Epoch 2/200
112/112 [==============================] - 0s 152us/sample - loss: 0.1973 - accuracy: 0.9732 - val_loss: 0.3707 - val_accuracy: 0.8684
Epoch 3/200
112/112 [==============================] - 0s 147us/sample - loss: 0.1959 - accuracy: 0.9732 - val_loss: 0.3697 - val_accuracy: 0.8684
Epoch 4/200
112/112 [==============================] - 0s 137us/sample - loss: 0.1952 - accuracy: 0.9732 - val_loss: 0.3693 - val_accuracy: 0.8684
Epoch 5/200
112/112 [==============================] - 0s 137us/sample - loss: 0.1951 - accuracy: 0.9732 - val_loss: 0.3690 - val_accuracy: 0.8684
Epoch 6/200
112/112 [==============================] - 0s 143us/sample - loss: 0.1937 - accuracy: 0.9732 - val_loss: 0.3681 - val_accuracy: 0.8684
Epoch 7/200
112/112 [==============================] - 0s 140us/sample - 

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_pred = np.round(model.predict(X_test))

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [138]:
results = model.evaluate(X_test, encoded_y_test)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

38/38 [==============================] - 0s 127us/sample - loss: 0.2691 - accuracy: 0.8947
Final test set loss: 0.269124
Final test set accuracy: 0.894737


In [142]:
#confusion matrix
from sklearn import metrics

cr=metrics.classification_report(encoded_y_test,y_pred)
print(cr)


              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.86      0.86      0.86        14
           2       0.86      0.92      0.89        13

   micro avg       0.89      0.89      0.89        38
   macro avg       0.90      0.90      0.90        38
weighted avg       0.90      0.89      0.90        38
 samples avg       0.89      0.89      0.89        38





---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [144]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
 from google.colab import files
 files.upload()

In [0]:
import pandas as pd
import numpy as np

In [0]:
sp_df=pd.read_csv("prices.csv")

In [0]:
sp_df.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

In [0]:
sp_df.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [147]:
# Dropping date and symbol columns
df = sp_df.drop(['date',"symbol"], axis=1)
df.head(5)

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [0]:
df.shape

(851264, 5)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
data=df.head(1000)

In [149]:
data.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [150]:
data.columns

Index(['open', 'close', 'low', 'high', 'volume'], dtype='object')

In [0]:
X = data.drop(['volume'], axis=1) 

In [0]:
y = data['volume']

In [153]:
y[0:10]

0    2163600.0
1    2386400.0
2    2489500.0
3    2006300.0
4    1408600.0
5    1098000.0
6     949600.0
7     785300.0
8    1093700.0
9    1523500.0
Name: volume, dtype: float64

In [0]:
y_sc= y/1000000

In [155]:
y_sc[0:10]

0    2.1636
1    2.3864
2    2.4895
3    2.0063
4    1.4086
5    1.0980
6    0.9496
7    0.7853
8    1.0937
9    1.5235
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X_np =  X.to_numpy()
y_np =  y_sc.to_numpy()

In [157]:
print(X_np.dtype, y_np.dtype)

float64 float64


In [0]:
X_np = np.float32(X_np)
y_np =   np.float32(y_np)

In [159]:
print(X_np.dtype, y_np.dtype)

float32 float32


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [160]:
X_np.ndim

2

In [0]:
X_nrm = tf.math.l2_normalize(X_np, axis=None, epsilon=1e-12, name=None)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
#number of features
n_features = X_nrm.shape[1]

In [0]:
# Hidden layers
n_neurons_1 = 512
n_neurons_2 = 256
n_neurons_3 = 128

In [0]:
bias_initializer = tf.zeros_initializer()
weight_initializer=tf.zeros_initializer()

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

In [0]:
@tf.function
def prediction(features, W, b):
    y_pred = tf.add(tf.matmul(features, W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [177]:
def train(X_nrm, y_np, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(X_nrm, w, b)
        current_loss = loss(y_np, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b
for i in range(100):    
    W, b = train(X_nrm, y_np, W, b)
    print('Current Training Loss on iteration', i, loss(y_np, prediction(X_nrm, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44553
Current Training Loss on iteration 15 223.835
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68655
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [178]:
print(W)

tf.Tensor(
[[0.0547828 ]
 [0.05488191]
 [0.05422735]
 [0.05533117]], shape=(4, 1), dtype=float32)


### Observe values of Bias
- Print the updated values

In [179]:
print(b)

tf.Tensor([4.607657], shape=(1,), dtype=float32)
