# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [2]:
from scipy import stats 
import numpy as np

In [12]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [78]:
#Null Hypothesis: Mean of runtime in GPU1 is zero
#𝐻0 : 𝜇 = 0
#Alternate  Hypothesis: Mean of runtime in GPU1 is not zero.
#𝐻𝐴: 𝜇 != 0 
from scipy.stats import ttest_1samp
print("Number of Elements in the Array is ",GPU1.size)
print("Mean Value of the array Sample ",GPU1.mean())
print("Standard deviation of Array Sample" ,GPU1.std())
SE=GPU1.std()/np.sqrt(GPU1.size)
print("Standard Error of GPU1",GPU1.std()/np.sqrt(GPU1.size))
print( "Testing Null Hypothesis myo=0, with Alpha=.05")
t_statistic, p_value = ttest_1samp(GPU1, 0)
if(p_value<.05):
    print("Reject Null Hypothesis, Conclusion Mean is not eaqual to Zero")
else:
    print("Accept the Null Hyposthesis")
#t_statistic, p_value = ttest_1samp(GPU1, 0)
print("P Value using One Sample T Test", p_value)

Number of Elements in the Array is  15
Mean Value of the array Sample  10.333333333333334
Standard deviation of Array Sample 1.1352924243950933
Standard Error of GPU1 0.29313124351717595
Testing Null Hypothesis myo=0, with Alpha=.05
Reject Null Hypothesis, Conclusion Mean is not eaqual to Zero
P Value using One Sample T Test 7.228892044970457e-15


## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [83]:
# Checking variance and size of the two datasets before using the Independent Sample T test.
print("Variance of Array GPU1",GPU1.var())
print("Variance of Array GPU2",GPU2.var())
print("Number of Elements in GPU1 is",GPU1.size)
print("Number of Elements in GPU2 is",GPU2.size)
print("Since both the series are independent and Normally distributed we run ttest_ind")
print("Rounding off to the first decimal the variances are same")
t_statistic, p_value=stats.ttest_ind(GPU1, GPU2, equal_var = True)
print("Comparing P value with Alpha, Rejecting Null Hypotheis if P<alpha")
if(p_value < 0.05):
    print("Reject Null Hypothesis As per Two Sample T Test")
else:
    print("Accept Nulll Hypothesis As per Two sample T test")

Variance of Array GPU1 1.2888888888888885
Variance of Array GPU2 1.3155555555555556
Number of Elements in GPU1 is 15
Number of Elements in GPU2 is 15
Since both the series are independent and Normally distributed we run ttest_ind
Rounding off to the first decimal the variances are same
Comparing P value with Alpha, Rejecting Null Hypotheis if P<alpha
Reject Null Hypothesis As per Two Sample T Test


## Question 3

He is trying a third GPU - GPU3.

In [43]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [46]:
# Checking variance and size of the two datasets before using the Independent Sample T test.
print("Variance of Array GPU1",GPU1.var())
print("Variance of Array GPU3",GPU3.var())
print("Number of Elements in GPU1 is",GPU1.size)
print("Number of Elements in GPU3 is",GPU3.size)
t_statistic, p_value=stats.ttest_ind(GPU1, GPU3, equal_var = False)
print("Comparing P value with Alpha, Rejecting Null Hypotheis if P < alpha")
if(p_value < 0.05):
    print("Reject Null Hypothesis As per Two Sample T Test")
else:
    print("Accept Null Hypothesis As per Two sample T test")

Variance of Array GPU1 1.2888888888888885
Variance of Array GPU3 2.0622222222222226
Number of Elements in GPU1 is 15
Number of Elements in GPU3 is 15
Comparing P value with Alpha, Rejecting Null Hypotheis if P < alpha
Accept Nulll Hypothesis As per Two sample T test


## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [64]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [92]:
from scipy import stats
print("The variance of e1 is",e1.var())
print("The variance of e2 is",e2.var())
print("The variance of e3 is",e3.var())
statistic,pvalue=stats.levene(e1,e2,e3)
f,p=stats.f_oneway(e1,e2,e3)
print("F Value is ",f)
print("Levents test statistic W is ", statistic)
print("W is greater than F, Hence reject null hypothesis that says variances are equalwe cannot depend on Anova results")


The variance of e1 is 0.5720623835687499
The variance of e2 is 0.3341299130026874
The variance of e3 is 0.16755628452275
F Value is  2.51357622845924
Levents test statistic W is  2.6741725711150446
W is greater than F, Hence reject null hypothesis that says variances are equalwe cannot depend on Anova results


## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [84]:
#𝐻0 : 𝜇1 = 𝜇2 or 𝜇2=𝜇3 or 𝜇1=𝜇3 or 𝜇1 =𝜇2 = 𝜇3
# ANOVA tests the null hypothesis that two or more groups have the same population mean
print("Mean value of e1 is",e1.mean())
print("Mean value of e2 is",e2.mean())
print("Mean value of e3 is",e3.mean())
#Anova test
f,p=stats.f_oneway(e1,e2,e3)
print("F Statastic for Anova is",f)
print("P Value for Anova is ", p)
if(p < 0.05):
    print("Reject Null Hypothesis As per one way Anova T Test")
else:
    print("Accept Null Hypothesis As per One way Anova T test")


Mean value of e1 is 0.7537925
Mean value of e2 is 1.69759475
Mean value of e3 is 0.7444685
F Statastic for Anova is 2.51357622845924
P Value for Anova is  0.13574644501798466
Accept Null Hypothesis As per One way Anova T test


## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

In [ ]:
Type 1 Error: Concluding a Failed experiment to be successfull. False Conclusion or false positive. It is concluding the experiment to be possitive by rejecting the null hypothesis while the actual result is negative.
Type 2 Error: Droping the experiment though it was successful. Fail to reject the null Hypothesis though the experiment is positive. 

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


Null Hypothesis: Mean waiting time is 4.5 minutes has not changed
𝐻0 : 𝜇 = 4.5.
Alternate  Hypothesis: Mean waiting time is less than 4.5 minutes. One tail test.
𝐻𝐴: 𝜇 < 4.5 minutes

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [103]:
import numpy as np

d1 = [5, 8, 3, 8]
d2 = [9, 6, 8, 5]
d3 = [8, 12, 7, 2]
d4 = [4, 16, 7, 3]
d5 = [3, 9, 6, 5]
d6 = [7, 2, 5, 7]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [88]:
# In this Example Output is independence of observed observed frequence which is categorical.
# Inputs d1,d2 d3 d4 d5 d6 are also Categorical
# When both Input and output are Categorical we go for Chi-Square test.
from scipy import stats
chi2, pval, dof, expected = stats.chi2_contingency(dice)
print("The chi2 stat is",chi2)
print("The P-value for the hypothesis test of independence is",pval)
print("The degrees of freedom are",dof)
print("The contingency table is \n",expected)

The chi2 stat is 23.315671914716496
The P-value for the hypothesis test of independence is 0.07766367301496693
The degrees of freedom are 15
The contingency table is 
 [[ 5.57419355  8.20645161  5.57419355  4.64516129]
 [ 6.50322581  9.57419355  6.50322581  5.41935484]
 [ 6.73548387  9.91612903  6.73548387  5.61290323]
 [ 6.96774194 10.25806452  6.96774194  5.80645161]
 [ 5.34193548  7.86451613  5.34193548  4.4516129 ]
 [ 4.87741935  7.18064516  4.87741935  4.06451613]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [116]:
from scipy import stats
new_d=stats.zscore(dice, axis = 0)
print("Z Scores for the the dice are \n",new_d)
p_values = stats.norm.sf(abs(new_d))
print("\n\nThe P Values from the Z scores are \n",p_values)
print("\n Mean of the array is",dice.mean())

Z Scores for the the dice are 
 [[-0.46291005 -0.18884739 -1.83711731  1.44115338]
 [ 1.38873015 -0.64208114  1.22474487  0.        ]
 [ 0.9258201   0.7176201   0.61237244 -1.44115338]
 [-0.9258201   1.62408759  0.61237244 -0.96076892]
 [-1.38873015  0.03776948  0.          0.        ]
 [ 0.46291005 -1.54854863 -0.61237244  0.96076892]]


The P Values from the Z scores are 
 [[0.32171442 0.42510621 0.03309629 0.07477068]
 [0.08245741 0.26041025 0.11033568 0.5       ]
 [0.17726974 0.23649578 0.27014569 0.07477068]
 [0.17726974 0.05217856 0.27014569 0.16833418]
 [0.08245741 0.48493574 0.5        0.5       ]
 [0.32171442 0.06074513 0.27014569 0.16833418]]

 Mean of the array is 6.458333333333333


## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [119]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [127]:
print("Mean value Before taking the drug is",before.mean())
print("Mean value After taking the drug is",after.mean())
scale_after=after.std()/np.sqrt(500)
print("Standard Eror after the drug is",scale_after)
print("95% Confidence Interval of weight reduction is",after.mean()-scale_after,"to",after.mean()+scale_after)
statistic,pvalue=stats.ttest_rel(before,after)
print("P value is ",pvalue)


Mean value Before taking the drug is 100.20563357465406
Mean value After taking the drug is 98.77018143333225
Standard Eror after the drug is 1.3851269206173842
95% Confidence Interval of weight reduction is 97.38505451271487 to 100.15530835394964
P value is  3.088529522767968e-10
