Data Description: Given a Bank customer, can we build a classifier that can determine whether they will leave
or not using Neural networks?

The dataset contains 10,000 sample points with 14 distinct features such as CustomerId, CreditScore, Geography, 
Gender, Age, Tenure, Balance etc. Know your data: https://www.kaggle.com/barelydedicated/bank-
customer-churn-modeling.

Businesses like banks which provide service have to worry about problem of 'Churn' i.e. customers leaving and
joining another service provider. It is important to understand which aspects of the service influence a
customer's decision in this regard. Management can concentrate efforts on improvement of service, keeping in 
mind these priorities.

The points distribution for this case is as follows:

Read the data set
Drop the columns which are unique for all users like IDs (2.5 points)
Distinguish the feature and target set (2.5 points)
Divide the data set into training and test sets ( 2.5 points)
Normalize the train and test data (5 points)
Initialize & build the model (10 points)
Predict the results using 0.5 as a threshold (5 points)
Print the Accuracy score and confusion matrix (2.5 points)

# Read the data set,Drop the columns which are unique for all users like IDs (2.5 points)

In [139]:
import numpy as np
import pandas as pd
bank_df=pd.read_csv("bank.csv")
print(bank_df.head())
print(" The column  names are features and the Target variable is Exited")

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [140]:
#Checking for null values
bank_df.isnull().sum()
drop_list=["CustomerId","Exited","Surname"]
new_bank_df=bank_df.drop(drop_list,axis=1)
new_bank_df.head()
bank_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Distinguish the feature and target set (2.5 points)

In [141]:
print(" The column  names are features and the Target variable is Exited")
new_bank_df.groupby(["Geography"]).count()

 The column  names are features and the Target variable is Exited


RowNumber  CreditScore  Gender   Age  Tenure  Balance  \
Geography                                                          
France          5014         5014    5014  5014    5014     5014   
Germany         2509         2509    2509  2509    2509     2509   
Spain           2477         2477    2477  2477    2477     2477   

           NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
Geography                                                             
France              5014       5014            5014             5014  
Germany             2509       2509            2509             2509  
Spain               2477       2477            2477             2477

# Encoding the Categorical Features Geography and Gender

In [142]:
#Encoding all the object data types.
new_bank_obj = new_bank_df.select_dtypes(include=['object']).copy()
cleanup_nums = {"Gender": {"Female": 0, "Male": 1 },"Geography":{"France": 0, "Germany": 1,"Spain":2 }}
X_df=new_bank_df.replace(cleanup_nums, inplace=False)# Replacing the categorical Target variable with the binary encoded values.
X_df.head()

RowNumber  CreditScore  Geography  Gender  Age  Tenure    Balance  \
0          1          619          0       0   42       2       0.00   
1          2          608          2       0   41       1   83807.86   
2          3          502          0       0   42       8  159660.80   
3          4          699          0       0   39       1       0.00   
4          5          850          2       0   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  
0              1          1               1        101348.88  
1              1          0               1        112542.58  
2              3          1               0        113931.57  
3              2          0               0         93826.63  
4              1          1               1         79084.10

In [143]:
X=X_df.values
#print("The following are the features\n",col_names)
Y_df=bank_df.iloc[:,13]
Y=Y_df.values
Y_df.head()
print(X_df.shape,Y_df.shape)
print("Target Set is \n",Y_df.head())

(10000, 11) (10000,)
Target Set is 
 0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64


# Divide the data set into training and test sets ( 2.5 points)

In [144]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=7)

In [145]:
print(X_train)

[[4.8820000e+03 5.7900000e+02 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 2.6149250e+04]
 [9.0000000e+01 6.3500000e+02 1.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.5679136e+05]
 [8.4600000e+02 5.0500000e+02 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3518011e+05]
 ...
 [5.7000000e+03 6.8400000e+02 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 8.7219410e+04]
 [5.3800000e+02 6.8600000e+02 2.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.2756980e+05]
 [9.4130000e+03 7.2500000e+02 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.3372057e+05]]


# Normalize the train and test data (5 points)

In [147]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [148]:
X_train

array([[-0.03769042, -0.7457425 , -0.90549962, ...,  0.64738759,
        -1.03667198, -1.28306535],
       [-1.69335299, -0.16469943,  0.30118964, ...,  0.64738759,
         0.96462528,  0.98168193],
       [-1.43215079, -1.51354942, -0.90549962, ..., -1.54466971,
        -1.03667198,  0.60703995],
       ...,
       [ 0.24493312,  0.34371326, -0.90549962, ...,  0.64738759,
         0.96462528, -0.22438313],
       [-1.5385665 ,  0.3644648 ,  1.5078789 , ...,  0.64738759,
        -1.03667198,  0.47511136],
       [ 1.52779521,  0.7691198 , -0.90549962, ..., -1.54466971,
        -1.03667198,  0.58173808]])

In [149]:
X_test

array([[-1.04103852e+00,  6.86113649e-01,  1.50787890e+00, ...,
        -1.54466971e+00, -1.03667198e+00,  1.29335321e+00],
       [-3.83541467e-01,  2.71082880e-01, -9.05499619e-01, ...,
         6.47387589e-01,  9.64625280e-01,  9.26435059e-01],
       [-1.70613669e+00,  1.42279326e+00, -9.05499619e-01, ...,
        -1.54466971e+00, -1.03667198e+00,  2.91500424e-01],
       ...,
       [-8.97653717e-01, -1.94386578e-02,  1.50787890e+00, ...,
         6.47387589e-01,  9.64625280e-01,  8.70720991e-01],
       [-4.33985276e-01,  1.50579942e+00,  3.01189639e-01, ...,
         6.47387589e-01,  9.64625280e-01, -9.31746731e-01],
       [ 8.55786921e-01,  1.31288066e-03,  3.01189639e-01, ...,
         6.47387589e-01,  9.64625280e-01, -4.21692933e-01]])

# Initialize & build the model (10 points)

In [150]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [151]:
tf.random.set_seed(42)

In [152]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [166]:
#Initialize Sequential model
model = Sequential()

In [167]:
#Add input layer
model.add(Dense(11, input_dim = 11, kernel_initializer = 'uniform', activation='relu', name='input_layer'))

In [168]:
#Add hidden layer
model.add(Dense(10, kernel_initializer = 'uniform', activation = 'relu', name='hidden_layer_1'))

In [169]:
#Add Output layer
model.add(Dense(1, kernel_initializer = 'uniform', activation = 'sigmoid', name='output_layer'))

In [170]:
#Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [171]:
print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 11)                132       
_________________________________________________________________
hidden_layer_1 (Dense)       (None, 10)                120       
_________________________________________________________________
output_layer (Dense)         (None, 1)                 11        
Total params: 263
Trainable params: 263
Non-trainable params: 0
_________________________________________________________________
None


In [172]:
# Fitting the ANN
model.fit(X_train,Y_train, epochs=100,validation_data=(X_test,Y_test))

Train on 7500 samples, validate on 2500 samples
Epoch 1/100
7500/7500 [==============================] - 3s 462us/sample - loss: 0.5464 - accuracy: 0.7961 - val_loss: 0.4418 - val_accuracy: 0.7960
Epoch 2/100
7500/7500 [==============================] - 2s 231us/sample - loss: 0.4367 - accuracy: 0.7964 - val_loss: 0.4353 - val_accuracy: 0.7960
Epoch 3/100
7500/7500 [==============================] - 2s 229us/sample - loss: 0.4306 - accuracy: 0.7964 - val_loss: 0.4313 - val_accuracy: 0.7960
Epoch 4/100
7500/7500 [==============================] - 2s 248us/sample - loss: 0.4249 - accuracy: 0.8023 - val_loss: 0.4258 - val_accuracy: 0.8184
Epoch 5/100
7500/7500 [==============================] - 2s 226us/sample - loss: 0.4186 - accuracy: 0.8232 - val_loss: 0.4218 - val_accuracy: 0.8300
Epoch 6/100
7500/7500 [==============================] - 2s 278us/sample - loss: 0.4137 - accuracy: 0.8344 - val_loss: 0.4170 - val_accuracy: 0.8300
Epoch 7/100
7500/7500 [==============================] - 2

7500/7500 [==============================] - 2s 217us/sample - loss: 0.3378 - accuracy: 0.8649 - val_loss: 0.3512 - val_accuracy: 0.8536
Epoch 56/100
7500/7500 [==============================] - 2s 207us/sample - loss: 0.3370 - accuracy: 0.8623 - val_loss: 0.3539 - val_accuracy: 0.8512
Epoch 57/100
7500/7500 [==============================] - 2s 210us/sample - loss: 0.3365 - accuracy: 0.8640 - val_loss: 0.3525 - val_accuracy: 0.8544
Epoch 58/100
7500/7500 [==============================] - 2s 208us/sample - loss: 0.3364 - accuracy: 0.8620 - val_loss: 0.3509 - val_accuracy: 0.8536
Epoch 59/100
7500/7500 [==============================] - 2s 214us/sample - loss: 0.3359 - accuracy: 0.8628 - val_loss: 0.3535 - val_accuracy: 0.8504
Epoch 60/100
7500/7500 [==============================] - 2s 209us/sample - loss: 0.3355 - accuracy: 0.8633 - val_loss: 0.3544 - val_accuracy: 0.8476
Epoch 61/100
7500/7500 [==============================] - 2s 205us/sample - loss: 0.3350 - accuracy: 0.8647 - val

# Predict the results using 0.5 as a threshold (5 points)

In [173]:
Y_pred = model.predict(X_test)

In [176]:
Y_pred = (Y_pred > 0.5).astype(np.int)
bank_test_predict=pd.DataFrame(X_test,columns=X_df.columns)
bank_test_predict["Predicted"]=Y_pred
bank_test_predict["Actual"]=bank_df["Exited"]
bank_test_predict.head()

RowNumber  CreditScore  Geography    Gender       Age    Tenure   Balance  \
0  -1.041039     0.686114   1.507879  0.916783 -0.370618 -1.386059 -1.234912   
1  -0.383541     0.271083  -0.905500 -1.090771  3.131735  1.025877 -1.234912   
2  -1.706137     1.422793  -0.905500 -1.090771 -0.559935 -0.007810 -1.234912   
3  -0.842718    -1.181525  -0.905500 -1.090771  1.333229 -0.696935 -1.234912   
4  -0.948098     0.686114   1.507879 -1.090771  0.008014  0.336752 -1.234912   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Predicted  \
0       2.520742  -1.544670       -1.036672         1.293353          0   
1       0.808126   0.647388        0.964625         0.926435          0   
2       0.808126  -1.544670       -1.036672         0.291500          0   
3      -0.904489   0.647388        0.964625        -0.151796          0   
4       0.808126   0.647388       -1.036672        -0.119396          0   

   Actual  
0       1  
1       0  
2       1  
3       0  
4       0

# Print the Accuracy score and confusion matrix (2.5 points)

In [177]:
from sklearn import metrics
print(metrics.classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.86      0.97      0.91      1990
           1       0.76      0.41      0.53       510

   micro avg       0.85      0.85      0.85      2500
   macro avg       0.81      0.69      0.72      2500
weighted avg       0.84      0.85      0.83      2500



In [178]:
print("accuracy", metrics.accuracy_score(Y_test, Y_pred))

accuracy 0.8528


In [179]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [180]:
print("Confusion Matrix \n")
print(cm)

Confusion Matrix 

[[1924   66]
 [ 302  208]]
